---
- name: Check Clickhouse connection from Vector hosts
  hosts: vector
  tasks:
    - name: Check Clickhouse connection
      ansible.builtin.shell: |
        if curl -s "http://{{ groups['clickhouse'][0] }}:8123" > /dev/null; then
          echo "Clickhouse is accessible"
          exit 0
        else
          echo "Clickhouse is not accessible"
          exit 1
        fi
      register: check_result
      changed_when: false

    - name: Show connection status
      ansible.builtin.debug:
        var: check_result.stdout_lines
